{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: request() got an unexpected keyword argument 'datas'", "trace": "self = <testcases.test_user.TestUser object at 0x00000228BAE52D90>\n\n    @pytest.mark.smoke\n    # 登录接口\n    def test_login(self):\n    \n        url = \"http://47.107.116.139/phpwind/index.php?m=u&c=login&a=dorun\"\n        data = {\n            \"username\": \"admim\",\n            \"password\": \"admim123\",\n            \"csrf_token\": read_yaml(\"access_token\"),\n            \"backurl\": \"http://47.107.116.139/phpwind/\",\n            \"invite\": \"\"\n        }\n        header ={\n            \"Accept\": \"application/json, text/javascript, /; q=0.01\",\n            \"X-Requested-With\": \"XMLHttpRequest\"\n        }\n    \n        # res=requests.request(method=\"post\",url=url,data=data,header=header,cookies=TestRequest.php_cookie)\n        # res=RequestUtil().send_request(method=\"post\",url=url,datas=data,headers=header)\n>       res=TestUser.sess.request(method=\"post\",url=url,datas=data,headers=header)\nE       TypeError: request() got an unexpected keyword argument 'datas'\n\ntestcases\\test_user.py:43: TypeError"}, "start": 1648040910426, "stop": 1648040910426, "uuid": "e97c8677-61b3-4057-92e5-ba1cb708bbc4", "historyId": "9f475056b86731e6f987ed0192674e5f", "testCaseId": "ae7787bf81b73fb49c236ce07912ea7f", "fullName": "testcases.test_user.TestUser#test_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-29T4IPBI"}, {"name": "thread", "value": "21588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user"}]}